# --- Base com dependências
FROM node:22.14.0-slim AS deps

WORKDIR /app

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

# --- Dev com volumes e hot reload
FROM node:22.14.0-slim

WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules

COPY apps/web ./apps/web

WORKDIR /app/apps/web

EXPOSE 3000

CMD ["yarn", "start:dev"]
