services:
  backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile.dev
    container_name: backend-kidstoystore
    platform: linux/x86_64
    ports:
      - 3333:3333
    networks:
      - kidstoystore
    volumes:
      - ./apps/backend/.env:/app/apps/backend/.env:delegated
      - ./apps/backend/src:/app/apps/backend/src:delegated
      - ./apps/backend/node_modules:/app/apps/backend/node_modules:delegated
      - ./packages:/app/packages:delegated
    env_file:
      - ./apps/backend/.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    container_name: db-kidstoystore
    platform: linux/x86_64
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kidstoystore
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U postgres -d kidstoystore'"]
      timeout: 10s
      retries: 5
    volumes:
      - pg:/var/lib/postgresql/data
    networks:
      - kidstoystore

networks:
  kidstoystore:
    driver: bridge

volumes:
  pg:
